In [100]:
# connect
from pytrends.request import TrendReq
pytrends = TrendReq(hl='ko', tz=540) # hl=host language, tz=time zone

# setting
kw_list = ["애플파이", "에그타르트", "슈크림"] # 단 게 땡기니까 달달구리구리한 것들로 키워드 리스트 생성
pytrends.build_payload(kw_list, cat=0, timeframe='2022-12-01 2022-12-7', geo='KR') 
pytrends.interest_over_time()

            애플파이  에그타르트  슈크림  isPartial
date
2022-12-01     0     40   51      False
2022-12-02     0      0   40      False
2022-12-03    93     47    0      False
2022-12-04    33     41    0      False
2022-12-05    85      0    0      False
2022-12-06     0      0    0      False
2022-12-07     0     28  100      False

In [101]:
pytrends.get_historical_interest(kw_list, year_start=2022, month_start=1, day_start=1, hour_start=0, year_end=2022, month_end=12, day_end=10, hour_end=0, cat=0, geo='', gprop='', sleep=0)

c:\ProgramData\Anaconda3\envs\dbtest\lib\site-packages\pytrends\request.py:589: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

c:\ProgramData\Anaconda3\envs\dbtest\lib\site-packages\pytrends\request.py:589: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

c:\ProgramData\Anaconda3\envs\dbtest\lib\site-packages\pytrends\request.py:589: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

c:\ProgramData\Anaconda3\envs\dbtest\lib\site-packages\pytrends\request.py:589: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

c:\ProgramData\Anaconda3\envs\dbtest\lib\site-packages\pytrends\request.py:589: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

c:\ProgramData\Anaconda3\envs\dbtest\lib\site-packages\pytrends\request.py:589: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

c:\ProgramData\Anaconda3\envs\dbtest\lib\site-packages\pytrends\request.py:589: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

c:\ProgramData\Anaconda3\envs\dbtest\lib\site-packages\pytrends\request.py:589: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

c:\ProgramData\Anaconda3\envs\dbtest\lib\site-packages\pytrends\request.py:589: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

c:\ProgramData\Anaconda3\envs\dbtest\lib\site-packages\pytrends\request.py:589: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

c:\ProgramData\Anaconda3\envs\dbtest\lib\site-packages\pytrends\request.py:589: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

c:\ProgramData\Anaconda3\envs\dbtest\lib\site-packages\pytrends\request.py:589: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

c:\ProgramData\Anaconda3\envs\dbtest\lib\site-packages\pytrends\request.py:589: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

c:\ProgramData\Anaconda3\envs\dbtest\lib\site-packages\pytrends\request.py:589: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

c:\ProgramData\Anaconda3\envs\dbtest\lib\site-packages\pytrends\request.py:589: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

c:\ProgramData\Anaconda3\envs\dbtest\lib\site-packages\pytrends\request.py:589: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

c:\ProgramData\Anaconda3\envs\dbtest\lib\site-packages\pytrends\request.py:589: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

c:\ProgramData\Anaconda3\envs\dbtest\lib\site-packages\pytrends\request.py:589: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

c:\ProgramData\Anaconda3\envs\dbtest\lib\site-packages\pytrends\request.py:589: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

c:\ProgramData\Anaconda3\envs\dbtest\lib\site-packages\pytrends\request.py:589: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

c:\ProgramData\Anaconda3\envs\dbtest\lib\site-packages\pytrends\request.py:589: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

c:\ProgramData\Anaconda3\envs\dbtest\lib\site-packages\pytrends\request.py:589: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

c:\ProgramData\Anaconda3\envs\dbtest\lib\site-packages\pytrends\request.py:589: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

c:\ProgramData\Anaconda3\envs\dbtest\lib\site-packages\pytrends\request.py:589: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

c:\ProgramData\Anaconda3\envs\dbtest\lib\site-packages\pytrends\request.py:589: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

c:\ProgramData\Anaconda3\envs\dbtest\lib\site-packages\pytrends\request.py:589: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

c:\ProgramData\Anaconda3\envs\dbtest\lib\site-packages\pytrends\request.py:589: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

c:\ProgramData\Anaconda3\envs\dbtest\lib\site-packages\pytrends\request.py:589: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

c:\ProgramData\Anaconda3\envs\dbtest\lib\site-packages\pytrends\request.py:589: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

c:\ProgramData\Anaconda3\envs\dbtest\lib\site-packages\pytrends\request.py:589: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

c:\ProgramData\Anaconda3\envs\dbtest\lib\site-packages\pytrends\request.py:589: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

c:\ProgramData\Anaconda3\envs\dbtest\lib\site-packages\pytrends\request.py:589: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

c:\ProgramData\Anaconda3\envs\dbtest\lib\site-packages\pytrends\request.py:589: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

c:\ProgramData\Anaconda3\envs\dbtest\lib\site-packages\pytrends\request.py:589: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

c:\ProgramData\Anaconda3\envs\dbtest\lib\site-packages\pytrends\request.py:589: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

c:\ProgramData\Anaconda3\envs\dbtest\lib\site-packages\pytrends\request.py:589: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

c:\ProgramData\Anaconda3\envs\dbtest\lib\site-packages\pytrends\request.py:589: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

c:\ProgramData\Anaconda3\envs\dbtest\lib\site-packages\pytrends\request.py:589: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

c:\ProgramData\Anaconda3\envs\dbtest\lib\site-packages\pytrends\request.py:589: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

c:\ProgramData\Anaconda3\envs\dbtest\lib\site-packages\pytrends\request.py:589: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

c:\ProgramData\Anaconda3\envs\dbtest\lib\site-packages\pytrends\request.py:589: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

c:\ProgramData\Anaconda3\envs\dbtest\lib\site-packages\pytrends\request.py:589: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

c:\ProgramData\Anaconda3\envs\dbtest\lib\site-packages\pytrends\request.py:589: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

c:\ProgramData\Anaconda3\envs\dbtest\lib\site-packages\pytrends\request.py:589: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

c:\ProgramData\Anaconda3\envs\dbtest\lib\site-packages\pytrends\request.py:589: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

c:\ProgramData\Anaconda3\envs\dbtest\lib\site-packages\pytrends\request.py:589: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

c:\ProgramData\Anaconda3\envs\dbtest\lib\site-packages\pytrends\request.py:589: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

c:\ProgramData\Anaconda3\envs\dbtest\lib\site-packages\pytrends\request.py:589: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

c:\ProgramData\Anaconda3\envs\dbtest\lib\site-packages\pytrends\request.py:589: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

c:\ProgramData\Anaconda3\envs\dbtest\lib\site-packages\pytrends\request.py:611: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

                     애플파이  에그타르트  슈크림  isPartial
date
2022-01-01 00:00:00     0      0    0      False
2022-01-01 01:00:00     0      0   24      False
2022-01-01 02:00:00     0      0    0      False
2022-01-01 03:00:00     0      0    0      False
2022-01-01 04:00:00    11      0    0      False
...                   ...    ...  ...        ...
2022-12-09 21:00:00     0     55    0      False
2022-12-09 22:00:00     0      0    0      False
2022-12-09 23:00:00     0      0   16      False
2022-12-10 00:00:00    17      0    0      False
2022-12-10 00:00:00    13     11    0      False

[8282 rows x 4 columns]

In [102]:
pytrends.interest_by_region(resolution='COUNTRY', inc_low_vol=True, inc_geo_code=True)

        geoCode  애플파이  에그타르트  슈크림
geoName
강원도       KR-42     0      0  100
경기도       KR-41    31     27   42
경상남도      KR-48     0      0  100
경상북도      KR-47     0      0  100
광주광역시     KR-29     0      0  100
대구광역시     KR-27    47      0   53
대전광역시     KR-30    21      0   79
부산광역시     KR-26    40      0   60
서울특별시     KR-11    35     28   37
울산광역시     KR-31     0      0  100
인천광역시     KR-28     0      0  100
전라남도      KR-46     0      0  100
전라북도      KR-45     0      0    0
제주특별자치도   KR-49     0      0    0
충청남도      KR-44     0      0  100
충청북도      KR-43     0      0    0

In [103]:
pytrends.related_topics()

{}

In [104]:
dic= pytrends.related_queries()
dic['애플파이']

{'top':      query  value
 0    애플 파일    100
 1   스포티 파이     69
 2       애플     66
 3  spotify     56
 4    애플 뮤직     51,
 'rising':      query    value
 0    애플 파일  9831450
 1   스포티 파이      300
 2  spotify      190}

In [105]:
# 급상승 검색어 오늘+어제
pytrends.trending_searches(pn='south_korea')

          0
0        정치
1        동지
2      자가진단
3       토트넘
4      프로골퍼
5       미사일
6     로스트아크
7       신현영
8       코레일
9        현빈
10    현대자동차
11       건설
12       자라
13     한국경제
14      이준석
15      아이폰
16      강수연
17     통화정책
18  불타는 트롯맨
19    고려대학교

In [106]:
pytrends.realtime_trending_searches(pn='IN') # realtime search trends for United States

,title,entityNames
0,"Coronavirus, China, India","[Coronavirus, China, India]"
1,"Srinivasa Ramanujan, National Mathematics Day,...","[Srinivasa Ramanujan, National Mathematics Day..."
2,"Vaikuntha Ekadashi, Tirumala Tirupati Devastha...","[Vaikuntha Ekadashi, Tirumala Tirupati Devasth..."
3,"2022, Christmas, December 22, Baptists","[2022, Christmas, December 22, Baptists]"
4,"Los Angeles Lakers, Sacramento Kings, NBA, Ant...","[Los Angeles Lakers, Sacramento Kings, NBA, An..."
5,"Sushant Singh Rajput, Aaditya Thackeray, Rhea ...","[Sushant Singh Rajput, Aaditya Thackeray, Rhea..."
6,"Vaccine, Sanofi Pasteur, Medicines and Healthc...","[Vaccine, Sanofi Pasteur, Medicines and Health..."
7,"Kevin Durant, Brooklyn Nets, Proposition bet, ...","[Kevin Durant, Brooklyn Nets, Proposition bet,..."
8,"Jaydev Unadkat, India national cricket team, T...","[Jaydev Unadkat, India national cricket team, ..."
9,"Coronavirus, Andhra Pradesh, Virus","[Coronavirus, Andhra Pradesh, Virus]"
10,"Jane Zhang, Coronavirus, China","[Jane Zhang, Coronavirus, China]"
11,"Common Admission Test (CAT), Indian Institute ...","[Common Admission Test (CAT), Indian Institute..."
12,"Saudi Arabia, Abaya, Examination, Burqa","[Saudi Arabia, Abaya, Examination, Burqa]"
13,"Manchester United F.C., Cristiano Ronaldo, EFL...","[Manchester United F.C., Cristiano Ronaldo, EF..."
14,"Vaccine, Bangladesh, Coronavirus","[Vaccine, Bangladesh, Coronavirus]"
15,"Reliance Capital, Finance, Hinduja Group, Reli...","[Reliance Capital, Finance, Hinduja Group, Rel..."
16,"Tirumala Tirupati Devasthanams, Vaikuntha, Ven...","[Tirumala Tirupati Devasthanams, Vaikuntha, Ve..."
17,"Amavasya, 2022","[Amavasya, 2022]"
18,"Sun Pharmaceutical Industries Ltd., Stock mark...","[Sun Pharmaceutical Industries Ltd., Stock mar..."
19,"Sula Vineyards, Stock market, Initial public o...","[Sula Vineyards, Stock market, Initial public ..."
20,"Academy Awards, Academy of Motion Picture Arts...","[Academy Awards, Academy of Motion Picture Art..."
21,"Suryakumar Yadav, India national cricket team,...","[Suryakumar Yadav, India national cricket team..."
22,"Coronavirus, California, December, Health care...","[Coronavirus, California, December, Health car..."
23,"Ukraine, Volodymyr Zelenskyy, Joe Biden, Ben R...","[Ukraine, Volodymyr Zelenskyy, Joe Biden, Ben ..."
24,"Bihar, Mathematics, Student, Srinivasa Ramanuj...","[Bihar, Mathematics, Student, Srinivasa Ramanu..."
25,"Zero waste, Adani Green Energy, Gautam Adani, ...","[Zero waste, Adani Green Energy, Gautam Adani,..."
26,"Ventilator, Uttar Pradesh, Medical college, Co...","[Ventilator, Uttar Pradesh, Medical college, C..."
27,"Indian Premier League, Sunrisers Hyderabad, Ma...","[Indian Premier League, Sunrisers Hyderabad, M..."
28,"Darshan Thoogudeepa, Sudeep","[Darshan Thoogudeepa, Sudeep]"

In [107]:
pytrends.top_charts(2022, hl='ko', tz=540, geo='KR')

               title       exploreQuery
0              기후 변화              기후 변화
1        이상한 변호사 우영우               우 영우
2          초단기 강수 예측          초단기 강수 예측
3  2022 FIFA 카타르 월드컵                월드컵
4             이태원 사고             이태원 압사
5  토트넘 대 K-League XI  토트넘 대 k league xi
6                수리남                수리남
7              우크라이나              우크라이나
8              로스트아크             로스트 아크
9              스승의 날             스승 의 날